# 개발용 단일 스테이지 이미지
FROM node:18-alpine
WORKDIR /app

ARG VITE_VUE_API_URL
ARG VITE_KAKAO_MAP_API_SERVICE_KEY
ENV VITE_VUE_API_URL=$VITE_VUE_API_URL
ENV VITE_KAKAO_MAP_API_SERVICE_KEY=$VITE_KAKAO_MAP_API_SERVICE_KEY

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

RUN npm install -g serve

EXPOSE 80
ENV PORT=80
CMD ["sh", "-c", "serve -s dist -l $PORT"]
